services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER:-mongo}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD:-example}
    depends_on:
      - mongo

  app:
    build:
      context: .
      args:
        - MONGODB_URI=${MONGODB_URI:-mongodb://root:example@mongo:27017}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://root:example@mongo:27017}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NODE_ENV=${NODE_ENV:-production}
      - AUTH_SECRET=${AUTH_SECRET:-Xl164kbH1y/ZZs9HvI56dZt2fgPn+1646OIvx18gOXc=}
      - GITHUB_SECRET=${GITHUB_SECRET:-""}
      - GITHUB_ID=${GITHUB_ID:-""}
    depends_on:
      - mongo

volumes:
  mongo-data:
